spring.application.name=Payment-Platform
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_platform
spring.datasource.username=postgres
spring.datasource.password=yash1912
spring.jpa.hibernate.ddl-auto=update
